package com.entities;
// Generated Jun 7, 2023, 10:12:20 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "jv5ecommerce")
public class Account implements java.io.Serializable {

	private Integer id;
	@NotBlank(message = "Vui lòng nhập tên!!!")
	private String name;
	@NotBlank(message = "Vui lòng nhập email!!!")
	@Email(message = "Vui lòng nhập đúng định dạng email!!!")
	private String email;
	@NotBlank(message = "Vui lòng nhập username!!!")
	private String username;
	@NotBlank(message = "Vui lòng nhập password!!!")
	private String password;
	private Integer role;
	private Set<Invoice> invoices = new HashSet<Invoice>(0);

	public Account() {
	}

	public Account(String name, String email, String username, String password, Integer role, Set<Invoice> invoices) {
		this.name = name;
		this.email = email;
		this.username = username;
		this.password = password;
		this.role = role;
		this.invoices = invoices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "username", length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "role")
	public Integer getRole() {
		return this.role;
	}

	public void setRole(Integer role) {
		this.role = role;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Invoice> getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set<Invoice> invoices) {
		this.invoices = invoices;
	}

}
