package com.entities;
// Generated Jun 7, 2023, 10:12:20 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "jv5ecommerce")
public class Product implements java.io.Serializable {

	private Integer id;
	private Category category;
	@NotBlank
	private String name;
	@NotNull
	private Double price;
	@NotNull
	private Integer quantity;
	private String image;
	private Set<Orders> orderses = new HashSet<Orders>(0);
	private Set<Productcolor> productcolors = new HashSet<Productcolor>(0);
	private Set<Productsize> productsizes = new HashSet<Productsize>(0);
	private Boolean status;

	public Product() {
	}

	public Product(Category category, String name, Double price, Integer quantity, String image, Set<Orders> orderses,
			Set<Productcolor> productcolors, Set<Productsize> productsizes) {
		this.category = category;
		this.name = name;
		this.price = price;
		this.quantity = quantity;
		this.image = image;
		this.orderses = orderses;
		this.productcolors = productcolors;
		this.productsizes = productsizes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoryid")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}
	
	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Productcolor> getProductcolors() {
		return this.productcolors;
	}

	public void setProductcolors(Set<Productcolor> productcolors) {
		this.productcolors = productcolors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Productsize> getProductsizes() {
		return this.productsizes;
	}

	public void setProductsizes(Set<Productsize> productsizes) {
		this.productsizes = productsizes;
	}

}
