package com.entities;
// Generated Jun 7, 2023, 10:12:20 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Size generated by hbm2java
 */
@Entity
@Table(name = "size", catalog = "jv5ecommerce")
public class Size implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Productsize> productsizes = new HashSet<Productsize>(0);

	public Size() {
	}

	public Size(String name, Set<Productsize> productsizes) {
		this.name = name;
		this.productsizes = productsizes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "size")
	public Set<Productsize> getProductsizes() {
		return this.productsizes;
	}

	public void setProductsizes(Set<Productsize> productsizes) {
		this.productsizes = productsizes;
	}

}
